---
- hosts: all

  vars_files:
    - ./vault.yml
    - ./vars.yml

  vars:
    ansible_ssh_pass: "{{ ssh_pass }}"
    ansible_become_pass: "{{ ssh_pass }}"

  tasks:
    - name: Update apt package manager
      become: true
      apt:
        update_cache: yes
    - name: Upgrade existing packages
      become: true
      apt:
        upgrade: dist
